cat_mapping = {
  "abduction":"abduction",
  "amputations":"other",
  "arbitrary arrest":"arbitrary arrest",
  "arbitrary detention":"arbitrary detention",
  "assault":"other",
  "child rights":"youth_children_s rights",
  "conscientious objection":"conscientious objector",
  "conscientious objector":"conscientious objector",
  "corporal punishment":"death penalty",
  "corporate abuse":"corporate abuse",
  "death by stoning":"other",
  "death in detention":"other",
  "death penalty":"death penalty",
  "death threats":"death threat",
  "death threatshuman rights defender":"death threat",
  "deathy penalty":"death penalty",
  "disappearance":"enforced disappearance",
  "enforced disappearance":"enforced disappearance",
  "enforced disappearances":"enforced disappearance",
  "excecution":"other",
  "excessive force":"excessive force",
  "execution":"other",
  "extradition":"forced eviction",
  "extrajudicial execution":"extrajudicial execution",
  "extrajudicial killing":"extrajudicial execution",
  "fear for safety":"fear for safety",
  "fear of safety":"fear for safety",
  "fear of torture":"fear of torture",
  "fines":"other",
  "firing squad":"death penalty",
  "flogging":"ill_treatment",
  "forced eviction":"forced eviction",
  "forced eviction families":"forced eviction",
  "forced evictions":"forced eviction",
  "forced labor":"other",
  "forced return":"forced return",
  "forcible return":"forced return",
  "freedom":"other",
  "freedom of assembly":"freedom of expression",
  "freedom of expression":"freedom of expression",
  "harassment":"harassment",
  "harrassment":"harassment",
  "harsh prison conditions":"harsh prison conditions",
  "healm":"other",
  "health concern":"health concern",
  "house arrest":"house arrest",
  "house destruction":"other",
  "housing condition":"other",
  "human rights":"other",
  "hunger strike":"hunger strike",
  "ill treatment":"ill_treatment",
  "imminent execution":"imminent execution",
  "impunity":"legal concern",
  "incommunicado":"incommunicado detention",
  "incommunicado detention":"incommunicado detention",
  "internet freedom":"freedom of expression",
  "intimidation":"harassment",
  "killing":"other",
  "land rights":"other",
  "legal concern":"legal concern",
  "lgbt issues":"lgbti rights",
  "lgbt rights":"lgbti rights",
  "life imprisonment":"other",
  "mass arrest":"mass arrest",
  "mass killings":"other",
  "medical action":"medical concern",
  "medical concern":"medical concern",
  "mental illness":"medical concern",
  "military courts":"other",
  "ngo risk":"other",
  "police brutality":"excessive force",
  "possible prisoner of conscience":"prisoner of conscience",
  "prison conditions":"harsh prison conditions",
  "prisoner conditions":"harsh prison conditions",
  "prisoner of conscience":"prisoner of conscience",
  "prisoners of conscience":"prisoner of conscience",
  "refugee issues":"refugee rights",
  "religious discrimination":"freedom of expression",
  "reproductive rights":"women_s rights",
  "right to life":"other",
  "right to work":"other",
  "risk for torture":"risk of torture",
  "risk if torture":"risk of torture",
  "risk of abduction":"other",
  "risk of arbitrary arrest":"arbitrary arrest",
  "risk of death":"other",
  "risk of deportation":"forced eviction",
  "risk of execution":"imminent execution",
  "risk of forced eviction":"forced eviction",
  "risk of forced psychiatric treatment":"health concern",
  "risk of forcible return":"forced return",
  "risk of torture":"risk of torture",
  "risk of unfair trial":"unfair trial",
  "sexual violence":"other",
  "solitary confinement":"other",
  "starvation":"other",
  "stoning":"other",
  "threats":"other",
  "tortur":"torture",
  "torture":"torture",
  "unfair trail":"unfair trial",
  "unfair trial":"unfair trial",
  "unjust arrest":"unjust arrest",
  "unjust imprisonment":"unjust imprisonment",
  "unlawful detention":"unjust imprisonment",
  "unlawful killing":"unlawful killing",
  "unlawful killings":"unlawful killing",
  "unlawful trial":"unfair trial",
  "urgent action":"other",
  "war on terror":"other",
  "war on terror uas":"other",
  "water rights":"other",
  "womans rights":"women_s rights"
}